server:
  servlet:
    context-path: /
  port: 2002

spring:
  application:
    name: kafka-demo-consumer
  # 连接kafka集群
  kafka:
    # 多个主机用逗号隔开
    bootstrap-servers: localhost:9092
    # 消费者
    consumer:
      # key与value的反序列化
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 标识此使用者所属的使用者组的唯一字符串
      group-id: boot-test-group
      #当 Kafka 中没有初始偏移量或服务器上不再存在当前偏移量时该怎么办:
      # earliest:当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，从头开始消费
      # latest:当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，消费新产生的该分区下的数据
      # none:topic各分区都存在已提交的offset时，从offset后开始消费；只要有一个分区不存在已提交的offset，则抛出异常
      # exception:直接抛出异常
      auto-offset-reset: latest